### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ksv1986** [ksv1986/wolf4sdl#1]
- [ ] Make SDL2 support a build-time switch
- [ ] Upgrade Visual Studio project to 2022
- [ ] Add haptic (rumble) support
